# Generated by Django 5.2 on 2025-10-02 13:03

import django.db.models.deletion
import job_lifecycle.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleaning_jobs', '0004_remove_cleaningjob_after_photos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('confirm_bid', 'Confirm Accepted Bid'), ('start_job', 'Start Job'), ('finish_job', 'Finish Job'), ('upload_photos', 'Upload Photos'), ('add_note', 'Add Note')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from the cleaner')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS latitude when action was performed', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS longitude when action was performed', max_digits=10, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='cleaning_jobs.cleaningjob')),
                ('performed_by', models.ForeignKey(help_text='User who performed this action', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['job', 'action_type'], name='job_lifecyc_job_id_19f4c7_idx'), models.Index(fields=['performed_at'], name='job_lifecyc_perform_7c9be2_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_change', 'Status Change'), ('bid_accepted', 'Bid Accepted'), ('cleaner_confirmed', 'Cleaner Confirmed'), ('job_started', 'Job Started'), ('job_finished', 'Job Finished'), ('client_reviewed', 'Client Reviewed'), ('photo_uploaded', 'Photo Uploaded'), ('note_added', 'Note Added')], max_length=20)),
                ('old_status', models.CharField(blank=True, help_text='Previous status before this event', max_length=20)),
                ('new_status', models.CharField(blank=True, help_text='New status after this event', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what happened')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event data (e.g., GPS coordinates, photo IDs, etc.)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='cleaning_jobs.cleaningjob')),
                ('triggered_by', models.ForeignKey(help_text='User who triggered this event (client, cleaner, or system)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['job', 'event_type'], name='job_lifecyc_job_id_935caa_idx'), models.Index(fields=['timestamp'], name='job_lifecyc_timesta_ef00d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('bid_accepted', 'Your bid was accepted!'), ('job_confirmed', 'Job confirmed by cleaner'), ('job_ready', 'Job ready to start'), ('job_started', 'Job has started'), ('job_finished', 'Job completed - please review'), ('payment_processed', 'Payment processed'), ('review_received', 'Review received')], max_length=20)),
                ('title', models.CharField(help_text='Short notification title', max_length=100)),
                ('message', models.TextField(help_text='Detailed notification message')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, help_text='Frontend URL for this notification action', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cleaning_jobs.cleaningjob')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='job_lifecyc_recipie_66acee_idx'), models.Index(fields=['created_at'], name='job_lifecyc_created_c11a73_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('before', 'Before Photo'), ('after', 'After Photo'), ('progress', 'Progress Photo')], max_length=10)),
                ('image', models.ImageField(help_text='Photo taken by cleaner for documentation', upload_to=job_lifecycle.models.job_photo_upload_path)),
                ('description', models.CharField(blank=True, help_text="Optional description of what the photo shows (e.g., 'Kitchen before cleaning')", max_length=200)),
                ('location_verified', models.BooleanField(default=False, help_text='Whether photo was taken at job location (future GPS verification)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_photos', to='cleaning_jobs.cleaningjob')),
                ('uploaded_by', models.ForeignKey(help_text='Cleaner who uploaded the photo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['job', 'photo_type'], name='job_lifecyc_job_id_26e0f3_idx'), models.Index(fields=['uploaded_at'], name='job_lifecyc_uploade_92c2f1_idx')],
            },
        ),
    ]
