# Generated by Django 5.2 on 2025-11-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_lifecycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobaction',
            name='action_type',
            field=models.CharField(choices=[('confirm_bid', 'Confirm Accepted Bid'), ('start_job', 'Start Job'), ('finish_job', 'Finish Job'), ('accept_completion', 'Accept Job Completion'), ('reject_completion', 'Reject Job Completion'), ('upload_photos', 'Upload Photos'), ('add_note', 'Add Note')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobnotification',
            name='notification_type',
            field=models.CharField(choices=[('bid_accepted', 'Your bid was accepted!'), ('job_confirmed', 'Job confirmed by cleaner'), ('job_ready', 'Job ready to start'), ('job_started', 'Job has started'), ('job_finished', 'Job completed - please review'), ('job_accepted', 'Client accepted your work'), ('job_rejected', 'Work needs revision'), ('payment_processed', 'Payment processed'), ('review_received', 'Review received')], max_length=20),
        ),
    ]
