# Generated by Django 5.2 on 2025-11-14 08:22

from django.db import migrations


def migrate_job_notifications_to_generic(apps, schema_editor):
    """
    Migrate JobNotification records to generic Notification model.
    This consolidates duplicate notification systems into one.
    
    Safety:
    - Only creates new records, doesn't delete old ones
    - Skips duplicates (checks if notification already exists)
    - Links to CleaningJob via ContentType framework
    """
    JobNotification = apps.get_model('job_lifecycle', 'JobNotification')
    Notification = apps.get_model('notifications', 'Notification')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Get CleaningJob content type
    try:
        cleaning_job_ct = ContentType.objects.get(app_label='cleaning_jobs', model='cleaningjob')
    except ContentType.DoesNotExist:
        print("⚠️ CleaningJob ContentType not found - skipping migration")
        return
    
    migrated_count = 0
    skipped_count = 0
    
    for jn in JobNotification.objects.all():
        # Check if already migrated (avoid duplicates)
        existing = Notification.objects.filter(
            recipient=jn.recipient,
            notification_type=jn.notification_type,
            content_type=cleaning_job_ct,
            object_id=jn.job.id,
            created_at=jn.created_at
        ).exists()
        
        if existing:
            print(f"⏭️ Skipping JobNotification #{jn.id} - already migrated")
            skipped_count += 1
            continue
        
        # Create generic notification
        Notification.objects.create(
            recipient=jn.recipient,
            sender=None,  # Job notifications don't have explicit sender
            notification_type=jn.notification_type,
            title=jn.title,
            message=jn.message,
            priority='medium',  # Default priority for job notifications
            content_type=cleaning_job_ct,
            object_id=jn.job.id,
            is_read=jn.is_read,
            read_at=jn.read_at,
            created_at=jn.created_at,
            action_url=jn.action_url or '',
            metadata={
                'migrated_from_job_notification': True,
                'original_job_notification_id': jn.id,
                'job_id': jn.job.id
            }
        )
        migrated_count += 1
        print(f"✅ Migrated JobNotification #{jn.id} → Notification (job={jn.job.id}, type={jn.notification_type})")
    
    print(f"\n📊 Migration complete: {migrated_count} migrated, {skipped_count} skipped")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration by deleting migrated notifications.
    Safe because we kept original JobNotification records.
    """
    Notification = apps.get_model('notifications', 'Notification')
    
    # Delete only notifications that were migrated from JobNotification
    deleted_count = Notification.objects.filter(
        metadata__migrated_from_job_notification=True
    ).count()
    
    Notification.objects.filter(
        metadata__migrated_from_job_notification=True
    ).delete()
    
    print(f"🔙 Reversed migration: {deleted_count} generic notifications deleted")


class Migration(migrations.Migration):

    dependencies = [
        ('job_lifecycle', '0002_alter_jobaction_action_type_and_more'),
        ('notifications', '0001_initial'),  # Ensure notifications app exists
        ('contenttypes', '0002_remove_content_type_name'),  # Ensure ContentType exists
    ]

    operations = [
        migrations.RunPython(
            migrate_job_notifications_to_generic,
            reverse_migration
        ),
    ]
