# Generated by Django 5.2 on 2025-11-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_lifecycle', '0003_migrate_notifications_to_generic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobNotification',
        ),
    ]
