# Generated by Django 5.2 on 2025-10-26 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_performance_optimizations'),
        ('cleaning_jobs', '0004_remove_cleaningjob_after_photos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('job', 'Job Chat'), ('direct', 'Direct Message'), ('support', 'Support Chat'), ('general', 'General Chat')], default='job', max_length=20),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_type', '-updated_at'], name='chat_room_type_idx'),
        ),
    ]
