# Generated by Django 5.2 on 2025-10-26 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_direct_message_type'),
        ('cleaning_jobs', '0004_remove_cleaningjob_after_photos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='bidder',
            field=models.ForeignKey(blank=True, help_text='The cleaner/bidder in this job chat. Required for job-type rooms.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidder_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='cleaning_jobs.cleaningjob'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['job', 'bidder'], name='chat_job_bidder_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('room_type', 'job')), fields=('job', 'bidder'), name='unique_job_bidder_chat'),
        ),
    ]
