# Generated by Django 5.2 on 2025-10-02 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningjob',
            name='services_requested',
        ),
        migrations.RemoveField(
            model_name='cleaningjob',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='cleaningjob',
            name='client_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Client's budget for this job", max_digits=10),
        ),
        migrations.AddField(
            model_name='cleaningjob',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final agreed price after bid acceptance', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cleaningjob',
            name='services_description',
            field=models.TextField(default='General cleaning services', help_text="Description of services needed (e.g., 'Deep clean 3-bedroom house, kitchen, 2 bathrooms')"),
        ),
        migrations.AlterField(
            model_name='cleaningjob',
            name='status',
            field=models.CharField(choices=[('open_for_bids', 'Open for Bids'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open_for_bids', max_length=20),
        ),
        migrations.CreateModel(
            name='JobBid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_amount', models.DecimalField(decimal_places=2, help_text="Cleaner's proposed price for the job", max_digits=10)),
                ('estimated_duration', models.DurationField(help_text='Estimated time to complete the job')),
                ('message', models.TextField(blank=True, help_text='Optional message from cleaner to client')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_bids', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='cleaning_jobs.cleaningjob')),
            ],
        ),
        migrations.AddField(
            model_name='cleaningjob',
            name='accepted_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_job', to='cleaning_jobs.jobbid'),
        ),
        migrations.AddIndex(
            model_name='jobbid',
            index=models.Index(fields=['job', 'status'], name='cleaning_jo_job_id_d71768_idx'),
        ),
        migrations.AddIndex(
            model_name='jobbid',
            index=models.Index(fields=['cleaner', 'status'], name='cleaning_jo_cleaner_f72983_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobbid',
            unique_together={('job', 'cleaner')},
        ),
    ]
