# Generated by Django 5.2 on 2025-10-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_jobs', '0002_remove_cleaningjob_services_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningjob',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, help_text='When cleaner actually finished the job', null=True),
        ),
        migrations.AddField(
            model_name='cleaningjob',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, help_text='When cleaner actually started the job', null=True),
        ),
        migrations.AddField(
            model_name='cleaningjob',
            name='after_photos',
            field=models.JSONField(blank=True, default=list, help_text='List of after photo URLs/paths taken by cleaner'),
        ),
        migrations.AddField(
            model_name='cleaningjob',
            name='before_photos',
            field=models.JSONField(blank=True, default=list, help_text='List of before photo URLs/paths taken by cleaner'),
        ),
        migrations.AddField(
            model_name='cleaningjob',
            name='cleaner_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When cleaner confirmed the accepted bid', null=True),
        ),
        migrations.AddField(
            model_name='cleaningjob',
            name='client_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Client rating from 1-5 stars', null=True),
        ),
        migrations.AddField(
            model_name='cleaningjob',
            name='client_review',
            field=models.TextField(blank=True, help_text="Client's review of the completed job"),
        ),
        migrations.AlterField(
            model_name='cleaningjob',
            name='status',
            field=models.CharField(choices=[('open_for_bids', 'Open for Bids'), ('bid_accepted', 'Bid Accepted - Awaiting Cleaner Confirmation'), ('confirmed', 'Confirmed by Cleaner'), ('ready_to_start', 'Ready to Start (30min window)'), ('in_progress', 'In Progress'), ('awaiting_review', 'Awaiting Client Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open_for_bids', max_length=20),
        ),
    ]
