# Generated by Django 5.2 on 2025-10-02 12:58

import cleaning_jobs.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_jobs', '0003_cleaningjob_actual_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningjob',
            name='after_photos',
        ),
        migrations.RemoveField(
            model_name='cleaningjob',
            name='before_photos',
        ),
        migrations.CreateModel(
            name='JobPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('before', 'Before Photo'), ('after', 'After Photo')], max_length=10)),
                ('image', models.ImageField(help_text='Photo taken by cleaner for documentation', upload_to=cleaning_jobs.models.job_photo_upload_path)),
                ('description', models.CharField(blank=True, help_text='Optional description of what the photo shows', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cleaning_jobs.cleaningjob')),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'photo_type'], name='cleaning_jo_job_id_14473c_idx')],
            },
        ),
    ]
