# Generated by Django 5.2 on 2025-11-11 12:03

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_jobs', '0004_remove_cleaningjob_after_photos_and_more'),
    ]

    operations = [
        # Enable pg_trgm extension for similarity matching and faster LIKE queries
        TrigramExtension(),
        
        # Enable unaccent extension for removing accents (helps with Greek text search)
        UnaccentExtension(),
    ]
