# Generated by Django 5.2 on 2025-11-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_jobs', '0005_enable_postgres_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPhoto',
        ),
    ]
