# Generated by Django 5.2 on 2025-11-08 17:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleaning_jobs', '0004_remove_cleaningjob_after_photos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_score', models.DecimalField(decimal_places=2, help_text='Matching score (0-100)', max_digits=5)),
                ('recommendation_rank', models.IntegerField(help_text='Rank in recommendation list')),
                ('quality_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pricing_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('specialization_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reliability_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('was_viewed', models.BooleanField(default=False)),
                ('was_contacted', models.BooleanField(default=False)),
                ('was_hired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for_jobs', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_recommendations', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaner_recommendations', to='cleaning_jobs.cleaningjob')),
            ],
        ),
        migrations.CreateModel(
            name='CleanerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Composite score from 0-100', max_digits=5)),
                ('quality_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Average quality rating (normalized to 0-100)', max_digits=5)),
                ('communication_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('professionalism_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('timeliness_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percentage of jobs completed (0-100)', max_digits=5)),
                ('on_time_rate', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percentage of jobs started on time', max_digits=5)),
                ('cancellation_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of jobs cancelled by cleaner', max_digits=5)),
                ('photo_documentation_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of jobs with before/after photos', max_digits=5)),
                ('bid_win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of bids that were accepted', max_digits=5)),
                ('avg_bid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average bid amount in dollars', max_digits=10)),
                ('avg_response_time_minutes', models.IntegerField(default=0, help_text='Average time to respond to messages (minutes)')),
                ('total_jobs', models.IntegerField(default=0, help_text='Total number of completed jobs')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('review_count', models.IntegerField(default=0, help_text='Total number of reviews received')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average overall rating (1-10 scale)', max_digits=4)),
                ('primary_property_type', models.CharField(blank=True, help_text='Most frequently cleaned property type', max_length=20)),
                ('eco_friendly_jobs_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('jobs_last_30_days', models.IntegerField(default=0)),
                ('jobs_last_90_days', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='False if no jobs in last 90 days')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('calculation_version', models.IntegerField(default=1, help_text='Version of scoring algorithm used')),
                ('cleaner', models.OneToOneField(limit_choices_to={'role': 'cleaner'}, on_delete=django.db.models.deletion.CASCADE, related_name='score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_score', models.DecimalField(decimal_places=2, help_text='Matching score (0-100)', max_digits=5)),
                ('recommendation_rank', models.IntegerField(help_text='Rank in recommendation list (1 = top recommendation)')),
                ('location_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pricing_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('specialization_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('availability_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('was_viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('was_bid_placed', models.BooleanField(default=False)),
                ('bid_placed_at', models.DateTimeField(blank=True, null=True)),
                ('was_bid_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation', to='cleaning_jobs.jobbid')),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='cleaning_jobs.cleaningjob')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('helpful', 'Helpful'), ('not_relevant', 'Not Relevant'), ('too_expensive', 'Too Expensive'), ('too_far', 'Too Far'), ('wrong_specialty', 'Wrong Specialty'), ('other', 'Other')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleaner_recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendations.cleanerrecommendation')),
                ('job_recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendations.jobrecommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BidSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_min', models.DecimalField(decimal_places=2, help_text='Minimum suggested bid (likely to win but lower profit)', max_digits=10)),
                ('suggested_optimal', models.DecimalField(decimal_places=2, help_text='Optimal bid (best balance of win probability and profit)', max_digits=10)),
                ('suggested_max', models.DecimalField(decimal_places=2, help_text='Maximum suggested bid (less likely to win but higher profit)', max_digits=10)),
                ('client_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_avg_bid', models.DecimalField(decimal_places=2, help_text='Average accepted bid for similar jobs', max_digits=10)),
                ('cleaner_avg_bid', models.DecimalField(decimal_places=2, help_text="Cleaner's historical average bid", max_digits=10)),
                ('cleaner_win_rate_at_suggested', models.DecimalField(decimal_places=2, help_text='Estimated win probability at optimal bid', max_digits=5)),
                ('current_bid_count', models.IntegerField(default=0)),
                ('current_lowest_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_bid_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual bid amount if cleaner placed a bid', max_digits=10, null=True)),
                ('was_bid_placed', models.BooleanField(default=False)),
                ('was_suggestion_used', models.BooleanField(default=False, help_text='True if actual bid is within 10% of suggested optimal')),
                ('did_win', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_suggestions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_suggestions', to='cleaning_jobs.cleaningjob')),
            ],
            options={
                'indexes': [models.Index(fields=['cleaner', '-created_at'], name='recommendat_cleaner_4aebef_idx'), models.Index(fields=['job'], name='recommendat_job_id_d0510c_idx')],
                'unique_together': {('job', 'cleaner')},
            },
        ),
        migrations.AddIndex(
            model_name='cleanerrecommendation',
            index=models.Index(fields=['job', '-recommendation_score'], name='recommendat_job_id_3d5927_idx'),
        ),
        migrations.AddIndex(
            model_name='cleanerrecommendation',
            index=models.Index(fields=['client', '-created_at'], name='recommendat_client__9633dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cleanerrecommendation',
            unique_together={('job', 'cleaner', 'client')},
        ),
        migrations.AddIndex(
            model_name='cleanerscore',
            index=models.Index(fields=['-overall_score'], name='recommendat_overall_f73412_idx'),
        ),
        migrations.AddIndex(
            model_name='cleanerscore',
            index=models.Index(fields=['-quality_score'], name='recommendat_quality_8d2570_idx'),
        ),
        migrations.AddIndex(
            model_name='cleanerscore',
            index=models.Index(fields=['is_active', '-overall_score'], name='recommendat_is_acti_ad0ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrecommendation',
            index=models.Index(fields=['cleaner', '-recommendation_score'], name='recommendat_cleaner_891540_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrecommendation',
            index=models.Index(fields=['job', '-recommendation_score'], name='recommendat_job_id_70518f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrecommendation',
            index=models.Index(fields=['-created_at'], name='recommendat_created_96a5c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobrecommendation',
            unique_together={('job', 'cleaner')},
        ),
        migrations.AddIndex(
            model_name='recommendationfeedback',
            index=models.Index(fields=['user', '-created_at'], name='recommendat_user_id_32821b_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationfeedback',
            index=models.Index(fields=['feedback_type'], name='recommendat_feedbac_b0a5cd_idx'),
        ),
    ]
