# Generated by Django 5.2 on 2025-11-02 17:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleaning_jobs', '0004_remove_cleaningjob_after_photos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('overall_rating', models.IntegerField(help_text='Overall rating from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(help_text='Detailed written review')),
                ('is_visible', models.BooleanField(default=True, help_text='False if review is hidden by admin moderation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(help_text='The completed job being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cleaning_jobs.cleaningjob')),
                ('reviewee', models.ForeignKey(help_text='User being reviewed (cleaner or client)', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(help_text='User who wrote this review (client or cleaner)', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewFlag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment or Bullying'), ('spam', 'Spam'), ('false_info', 'False Information'), ('other', 'Other')], help_text='Reason for flagging', max_length=20)),
                ('details', models.TextField(blank=True, help_text='Optional additional details about why this review was flagged')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('action_taken', 'Action Taken'), ('dismissed', 'Dismissed')], default='pending', help_text='Current moderation status', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about the flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When admin reviewed this flag', null=True)),
                ('flagger', models.ForeignKey(help_text='User who flagged this review', on_delete=django.db.models.deletion.CASCADE, related_name='review_flags', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(help_text='The review being flagged', on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='reviews.review')),
            ],
            options={
                'ordering': ['moderation_status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('quality', 'Quality of Work'), ('communication', 'Communication'), ('professionalism', 'Professionalism'), ('timeliness', 'Timeliness')], help_text='Aspect being rated', max_length=20)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('review', models.ForeignKey(help_text='The review this rating belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='reviews.review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('response_text', models.TextField(help_text="Reviewee's response to the review")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.OneToOneField(help_text='The review being responded to', on_delete=django.db.models.deletion.CASCADE, related_name='response', to='reviews.review')),
            ],
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewee', '-created_at'], name='reviews_rev_reviewe_f0f3ae_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['job'], name='reviews_rev_job_id_45562c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer'], name='reviews_rev_reviewe_e817a5_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_visible', '-created_at'], name='reviews_rev_is_visi_d4dedd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('job', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='reviewflag',
            index=models.Index(fields=['moderation_status', '-created_at'], name='reviews_rev_moderat_c2c0bd_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewflag',
            index=models.Index(fields=['review'], name='reviews_rev_review__c51789_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewflag',
            unique_together={('review', 'flagger')},
        ),
        migrations.AddIndex(
            model_name='reviewrating',
            index=models.Index(fields=['review', 'category'], name='reviews_rev_review__a20940_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewrating',
            unique_together={('review', 'category')},
        ),
        migrations.AddIndex(
            model_name='reviewresponse',
            index=models.Index(fields=['review'], name='reviews_rev_review__989a48_idx'),
        ),
    ]
