# Generated by Django 5.2 on 2025-10-26 10:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cleaning_jobs', '0004_remove_cleaningjob_after_photos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total payment amount in dollars', max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform fee amount (percentage of total)', max_digits=10)),
                ('cleaner_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to be paid to cleaner after platform fee', max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=255, null=True, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, help_text='Stripe Charge ID after successful payment', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('currency', models.CharField(default='usd', help_text='Currency code (ISO 4217)', max_length=3)),
                ('description', models.TextField(blank=True, help_text='Payment description or notes')),
                ('payment_method_type', models.CharField(blank=True, help_text='Type of payment method (card, bank_transfer, etc.)', max_length=50)),
                ('payment_method_last4', models.CharField(blank=True, help_text='Last 4 digits of card/account', max_length=4)),
                ('payment_method_brand', models.CharField(blank=True, help_text='Card brand (Visa, Mastercard, etc.)', max_length=50)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount refunded', max_digits=10)),
                ('refund_reason', models.TextField(blank=True, help_text='Reason for refund (if applicable)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was successfully completed', null=True)),
                ('refunded_at', models.DateTimeField(blank=True, help_text='When payment was refunded', null=True)),
                ('cleaner', models.ForeignKey(help_text='The cleaner receiving the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaner_payments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(help_text='The client making the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_payments', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(help_text='The cleaning job this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cleaning_jobs.cleaningjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to refund', max_digits=10)),
                ('reason', models.CharField(choices=[('requested_by_client', 'Requested by Client'), ('service_not_provided', 'Service Not Provided'), ('poor_quality', 'Poor Quality'), ('cleaner_cancelled', 'Cleaner Cancelled'), ('duplicate_payment', 'Duplicate Payment'), ('fraudulent', 'Fraudulent'), ('other', 'Other')], default='requested_by_client', max_length=50)),
                ('reason_details', models.TextField(blank=True, help_text='Additional details about refund reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('stripe_refund_id', models.CharField(blank=True, help_text='Stripe Refund ID', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When refund was processed', null=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stripe_account_id', models.CharField(help_text='Stripe Connect account ID', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Setup'), ('active', 'Active'), ('restricted', 'Restricted'), ('disabled', 'Disabled')], db_index=True, default='pending', max_length=20)),
                ('charges_enabled', models.BooleanField(default=False, help_text='Whether the account can accept charges')),
                ('payouts_enabled', models.BooleanField(default=False, help_text='Whether the account can receive payouts')),
                ('details_submitted', models.BooleanField(default=False, help_text='Whether cleaner has completed onboarding')),
                ('onboarding_link', models.URLField(blank=True, help_text='Stripe onboarding URL (temporary)')),
                ('onboarding_link_expires_at', models.DateTimeField(blank=True, help_text='When the onboarding link expires', null=True)),
                ('bank_account_last4', models.CharField(blank=True, help_text='Last 4 digits of bank account', max_length=4)),
                ('bank_name', models.CharField(blank=True, help_text='Name of bank', max_length=100)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total earnings (before platform fee)', max_digits=12)),
                ('total_payouts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid out to cleaner', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text='When account was fully activated', null=True)),
                ('cleaner', models.OneToOneField(limit_choices_to={'role': 'cleaner'}, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('charge', 'Charge'), ('payout', 'Payout'), ('refund', 'Refund'), ('platform_fee', 'Platform Fee'), ('adjustment', 'Adjustment')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('stripe_transfer_id', models.CharField(blank=True, help_text='Stripe Transfer ID (for Connect payouts)', max_length=255)),
                ('stripe_payout_id', models.CharField(blank=True, help_text='Stripe Payout ID', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When transaction was completed', null=True)),
                ('from_user', models.ForeignKey(blank=True, help_text='User money is coming from (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_from', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.payment')),
                ('to_user', models.ForeignKey(blank=True, help_text='User money is going to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['job', 'status'], name='payments_pa_job_id_dde10c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client', 'status'], name='payments_pa_client__39a683_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['cleaner', 'status'], name='payments_pa_cleaner_867717_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__6fe52c_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status'], name='payments_re_payment_4444a0_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', 'created_at'], name='payments_re_status_698972_idx'),
        ),
        migrations.AddIndex(
            model_name='stripeaccount',
            index=models.Index(fields=['cleaner', 'status'], name='payments_st_cleaner_259426_idx'),
        ),
        migrations.AddIndex(
            model_name='stripeaccount',
            index=models.Index(fields=['stripe_account_id'], name='payments_st_stripe__960115_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment', 'transaction_type'], name='payments_tr_payment_2793b0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['from_user', 'status'], name='payments_tr_from_us_db2ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['to_user', 'status'], name='payments_tr_to_user_aaed18_idx'),
        ),
    ]
