# Generated by Django 5.2 on 2025-11-02 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount the cleaner is requesting to withdraw', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('stripe_transfer_id', models.CharField(blank=True, help_text='Stripe transfer ID when funds are sent to cleaner', max_length=255)),
                ('stripe_payout_id', models.CharField(blank=True, help_text="Stripe payout ID when funds reach cleaner's bank", max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if payout was denied')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the payout was actually processed by Stripe', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal admin notes about this payout')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this payout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payout_requests', to=settings.AUTH_USER_MODEL)),
                ('cleaner', models.ForeignKey(help_text='The cleaner requesting the payout', on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payout_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['cleaner', 'status'], name='payout_requ_cleaner_7fef5d_idx'), models.Index(fields=['status', 'requested_at'], name='payout_requ_status_7d2657_idx')],
            },
        ),
    ]
