# Generated by Django 5.2 on 2025-10-02 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(choices=[('city', 'City/Town'), ('radius', 'Radius from location'), ('postal_codes', 'Postal codes')], default='city', max_length=20)),
                ('area_name', models.CharField(help_text="Name of the service area (e.g., 'Manhattan', 'Brooklyn')", max_length=255)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='US', max_length=100)),
                ('center_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('center_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('radius_miles', models.PositiveIntegerField(blank=True, help_text='Service radius in miles', null=True)),
                ('postal_codes', models.JSONField(blank=True, default=list, help_text='List of postal codes served')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority order (1 = highest)')),
                ('max_travel_time_minutes', models.PositiveIntegerField(default=30, help_text='Maximum travel time to job site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleaner', models.ForeignKey(limit_choices_to={'role': 'cleaner'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cleaner', 'priority', 'area_name'],
                'unique_together': {('cleaner', 'area_name')},
            },
        ),
    ]
