# Generated by Django 5.2 on 2025-10-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_servicearea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='radius_miles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Service radius in miles (decimal allowed for km conversion)', max_digits=6, null=True),
        ),
    ]
