# Generated by Django 5.2 on 2025-10-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_servicearea_radius_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect Account ID for cleaners (receiving payouts)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID for clients (payment processing)', max_length=255, null=True, unique=True),
        ),
    ]
