# Generated by Django 5.2 on 2025-11-09 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_stripe_account_id_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text="Whether user's email has been verified"),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='When email was verified', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_cleaner',
            field=models.BooleanField(default=False, help_text='Admin-verified cleaner (ID and resume checked)'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes about verification (private, not shown to user)'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When cleaner was verified by admin', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified this cleaner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cleaners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, help_text='Token for email verification', max_length=255, null=True),
        ),
    ]
