# Generated by Django 5.2 on 2025-11-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_email_verified_user_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_token_expires',
            field=models.DateTimeField(blank=True, help_text='Expiration time for verification token (30 minutes after generation)', null=True),
        ),
    ]
