# Generated by Django 5.2 on 2025-11-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_verification_token_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Whether user has enabled two-factor authentication'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, help_text='TOTP secret key for 2FA (base32 encoded)', max_length=32, null=True),
        ),
    ]
