# Generated by Django 5.2 on 2025-11-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_two_factor_enabled_user_two_factor_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_timezone',
            field=models.CharField(default='Europe/Athens', help_text="User's timezone (e.g., 'Europe/Athens', 'America/New_York'). Used for job scheduling and timing validation.", max_length=50),
        ),
    ]
